name = "Code GD5 (alpha)"
release_date = "2025-01-01"
last_updated = "2025-01-01"
attachment = true
reasoning = true
temperature = false
knowledge = "2025-01-01"
tool_call = true
structured_output = true
open_weights = false

[cost]
input = 1.5
output = 15
cache_read = 0.3

[limit]
context = 400_000
output = 128_000

[modalities]
input = ["text", "image"]
output = ["text"]

[provider]
npm = "@ai-sdk/openai"
