name = "GLM 4.5 Air (Thinking)"
release_date = "2025-04-07"
last_updated = "2025-12-24"
attachment = false
reasoning = true
tool_call = true
structured_output = true
open_weights = false

[cost]
input = 0.1
output = 0.1

[limit]
context = 128_000
input = 128_000
output = 98_304

[modalities]
input = ["text"]
output = ["text"]
