name = "Llama-3.1-405B-Instruct"
attachment = false
reasoning = false
tool_call = true
structured_output = true
temperature = true
knowledge = "2024-12"
release_date = "2025-01-20"
last_updated = "2026-02-04"
open_weights = true
status = "deprecated"

[cost]
input = 1.00
output = 3.00
cache_read = 0.10
cache_write = 1.25

[limit]
context = 131_072
input = 124_000
output = 8_192

[modalities]
input = ["text"]
output = ["text"]