name = "Gemini-3.0-Pro"
release_date = "2025-10-22"
last_updated = "2025-10-22"
attachment = true
reasoning = null
temperature = false
open_weights = false
tool_call = null

[cost]
input = 1.6
output = 9.6
cache_read = 0.16

[limit]
context = 1_048_576
output = null

[modalities]
input = ["text", "image", "video", "audio"]
output = ["text"]
